In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('sample_pandas.csv')
df

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [4]:
df.shape

(500, 12)

In [5]:
df.columns

Index(['first_name', 'last_name', 'company_name', 'address', 'city', 'county',
       'state', 'zip', 'phone1', 'phone2', 'email', 'web'],
      dtype='str')

In [6]:
df.info

<bound method DataFrame.info of     first_name  last_name                   company_name  \
0        James       Butt              Benton, John B Jr
1    Josephine    Darakjy          Chanay, Jeffrey A Esq
2          Art     Venere            Chemel, James L Cpa
3        Lenna   Paprocki         Feltz Printing Service
4      Donette     Foller            Printing Dimensions
..         ...        ...                            ...
495    Brittni  Gillaspie                    Inner Label
496    Raylene      Kampa                     Hermar Inc
497        Flo   Bookamer   Simonton Howe & Schneider Pc
498       Jani      Biddy  Warehouse Office & Paper Prod
499   Chauncey     Motley     Affiliated With Travelodge

                  address        city      county state    zip        phone1  \
0      6649 N Blue Gum St         NaN     Orleans    LA  70116  504-621-8927
1     4 B Blue Ridge Blvd    Brighton  Livingston    MI  48116  810-292-9388
2    8 W Cerritos Ave #54  Bridgeport  Gloucester    NJ   8014  856-636-8749
3             639 Main St   Anchorage   Anchorage    AK  99501  907-385-4412
4            34 Center St    Hamilton      Butler    OH  45011  513-570-1893
..                    ...         ...         ...   ...    ...           ...
495            67 Rv Cent       Boise         Ada    ID  83709  208-709-1235
496        2 Sw Nyberg Rd     Elkhart     Elkhart    IN  46514  574-499-1454
497       89992 E 15th St    Alliance   Box Butte    NE  69301  308-726-2182
498      61556 W 20th Ave     Seattle        King    WA  98104  206-711-6498
499        63 E Aurora Dr     Orlando      Orange    FL  32804  407-413-4842

           phone2                          email  \
0    504-845-1427                jbutt@gmail.com
1    810-374-9840  josephine_darakjy@darakjy.org
2    856-264-4130                 art@venere.org
3    907-921-2010          lpaprocki@hotmail.com
4    513-549-4561         donette.foller@cox.net
..            ...                            ...
495  208-206-9848       bgillaspie@gillaspie.com
496  574-330-1884               rkampa@kampa.org
497  308-250-6987           flo.bookamer@cox.net
498  206-395-6284               jbiddy@yahoo.com
499  407-557-8857        chauncey_motley@aol.com

                                         web
0               http://www.bentonjohnbjr.com
1           http://www.chanayjeffreyaesq.com
2             http://www.chemeljameslcpa.com
3        http://www.feltzprintingservice.com
4          http://www.printingdimensions.com
..                                       ...
495                http://www.innerlabel.com
496                 http://www.hermarinc.com
497   http://www.simontonhoweschneiderpc.com
498  http://www.warehouseofficepaperprod.com
499  http://www.affiliatedwithtravelodge.com

[500 rows x 12 columns]>

In [7]:
df.isnull().sum()

first_name      0
last_name       0
company_name    0
address         0
city            1
county          0
state           0
zip             0
phone1          0
phone2          0
email           0
web             0
dtype: int64

In [10]:
# Create a new column
df['full_name'] = df['first_name'] + ' ' + df['last_name']
df['email_domain']= df['email'].str.split('@').str[-1]
df['website_domain'] = df['web'].str.split('//').str[-1].str.split('/').str[0]
df[['full_name' , 'email_domain', 'website_domain']].head()

           full_name email_domain                website_domain
0         James Butt    gmail.com         www.bentonjohnbjr.com
1  Josephine Darakjy  darakjy.org     www.chanayjeffreyaesq.com
2         Art Venere   venere.org       www.chemeljameslcpa.com
3     Lenna Paprocki  hotmail.com  www.feltzprintingservice.com
4     Donette Foller      cox.net    www.printingdimensions.com

In [11]:
# Selected specific columns
selected_columns = df[['full_name', 'email_domain','website_domain' ]]
print(selected_columns.head())

           full_name email_domain                website_domain
0         James Butt    gmail.com         www.bentonjohnbjr.com
1  Josephine Darakjy  darakjy.org     www.chanayjeffreyaesq.com
2         Art Venere   venere.org       www.chemeljameslcpa.com
3     Lenna Paprocki  hotmail.com  www.feltzprintingservice.com
4     Donette Foller      cox.net    www.printingdimensions.com

In [14]:
# selected filetred data
ca_users = df[df['state'] == 'CA']
ca_users.head()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web,full_name,email_domain,website_domain
7,Leota,Dilliard,Commercial Press,7 W Jackson Blvd,San Jose,Santa Clara,CA,95111,408-752-3500,408-813-1105,leota@hotmail.com,http://www.commercialpress.com,Leota Dilliard,hotmail.com,www.commercialpress.com
12,Kiley,Caldarera,Feiner Bros,25 E 75th St #69,Los Angeles,Los Angeles,CA,90034,310-498-5651,310-254-3084,kiley.caldarera@aol.com,http://www.feinerbros.com,Kiley Caldarera,aol.com,www.feinerbros.com
21,Veronika,Inouye,C 4 Network Inc,6 Greenleaf Ave,San Jose,Santa Clara,CA,95111,408-540-1785,408-813-4592,vinouye@aol.com,http://www.cnetworkinc.com,Veronika Inouye,aol.com,www.cnetworkinc.com
37,Rozella,Ostrosky,Parkway Company,17 Morena Blvd,Camarillo,Ventura,CA,93012,805-832-6163,805-609-1531,rozella.ostrosky@ostrosky.com,http://www.parkwaycompany.com,Rozella Ostrosky,ostrosky.com,www.parkwaycompany.com
47,Kanisha,Waycott,"Schroer, Gene E Esq",5 Tomahawk Dr,Los Angeles,Los Angeles,CA,90006,323-453-2780,323-315-7314,kanisha_waycott@yahoo.com,http://www.schroergeneeesq.com,Kanisha Waycott,yahoo.com,www.schroergeneeesq.com

In [16]:
# sorting
sorted_users = df.sort_values(by = 'last_name')
sorted_users[['first_name', 'last_name' ]].head()

    first_name  last_name
71    Johnetta   Abdallah
262   Geoffrey       Acey
351     Weldon      Acuff
316     Barbra      Adkin
203     Fausto  Agramonte

In [15]:
len(ca_users)

72

In [17]:
# Grouping state and counting users
state_counts = df.groupby('state').size().reset_index(name = 'user_count')
print(state_counts)

   state  user_count
0     AK           6
1     AR           1
2     AZ           9
3     CA          72
4     CO           8
5     CT           5
6     DC           1
7     FL          28
8     GA           7
9     HI           4
10    IA           1
11    ID           4
12    IL          15
13    IN           9
14    KS           5
15    KY           1
16    LA           9
17    MA          12
18    MD          17
19    ME           3
20    MI          14
21    MN           7
22    MO           4
23    MS           4
24    MT           1
25    NC           8
26    ND           1
27    NE           2
28    NH           1
29    NJ          52
30    NM           2
31    NV           2
32    NY          46
33    OH          22
34    OK           1
35    OR           6
36    PA          29
37    RI           5
38    SC           3
39    SD           1
40    TN          10
41    TX          32
42    UT           1
43    VA           7
44    WA           8
45    WI          11
46    WY           3

In [ ]:
# export manipulated data-->yo name ko csv file banayo with the data of the sample_pandas.csv
df.to_csv('manipulated_users.csv' , index = False)
print("CSV file exported successfully.")

CSV file exported successfully.